# Generated by Django 4.2.2 on 2023-06-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(default='', max_length=100)),
                ('code', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Активна'), ('inactive', 'Отключена')], max_length=100, null=True)),
                ('activity', models.CharField(choices=[('registered', 'Зарегистрирован'), ('game', 'Играет'), ('pause', 'Пауза'), ('removed', 'Удален')], max_length=100, null=True)),
            ],
        ),
    ]
