# Generated by Django 4.2.1 on 2023-05-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BotUser",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("userid", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100)),
                ("lock_trade", models.CharField(max_length=100)),
                ("date", models.CharField(max_length=100)),
            ],
        ),
    ]
